{{- if .Values.data.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pdns.fullname" . }}-data
  labels:
    {{- include "pdns.labels" . | nindent 4 }}
data:
  forward_zones.conf: |
    {{- .Values.data.forwardZones | nindent 4 }}
{{- end }}
