---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pdns.fullname" . }}
  labels:
    {{- include "pdns.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pdns.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pdns.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pdns.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}{{- if not (hasPrefix "@" (.Values.image.tag | default .Chart.AppVersion)) -}}:{{- end -}}{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            {{- if .Values.service.http.enabled }}
            - name: http
              containerPort: {{ .Values.service.http.containerPort }}
              protocol: TCP
            {{- end }}
            - name: tcp-dns
              containerPort: 53
              protocol: TCP
            - name: udp-dns
              containerPort: 53
              protocol: UDP
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or .Values.data.enabled .Values.additionalVolumes }}
          volumeMounts:
          {{- if .Values.data.enabled }}
            - name: data
              mountPath: /etc/pdns/forward_zones.conf
              subPath: forward_zones.conf
          {{- end }}
          {{- if .Values.additionalVolumeMounts }}
            {{ toYaml .Values.additionalVolumeMounts | nindent 12 }}
          {{- end }}
          {{- end }}
      {{- if or .Values.data.enabled .Values.additionalVolumes }}
      volumes:
      {{- if .Values.data.enabled }}
        - name: data
          configMap:
            name: {{ include "pdns.fullname" . }}-data
      {{- end }}
      {{- if .Values.additionalVolumes }}
        {{ toYaml .Values.additionalVolumes | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
